#' Estimate Parameters From Real Datasets by Splat
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{splatEstimate} function in Splatter package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom splatter splatEstimate
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
Splat_estimation <- function(ref_data, verbose = FALSE, seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("splatter", quietly = TRUE)){
    cat("Splatter is not installed on your device\n")
    cat("Installing splatter...\n")
    BiocManager::install("splatter")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using Splat\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- splatter::splatEstimate(ref_data)
      )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by Splat
#'
#' @param ref_data NULL or reference data if you want to simulate trajectory data.
#' @param parameters A object generated by \code{\link[splatter]{splatEstimate}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom splatter getParams setParam splatSimulate
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#' @importFrom SingleCellExperiment counts colData rowData
#' @importFrom Seurat as.Seurat
#' @importFrom SeuratDisk SaveH5Seurat Convert
#' @importFrom stringr str_replace
#'
#' @export
#'
Splat_simulation <- function(ref_data = NULL,
                             parameters,
                             other_prior,
                             return_format,
                             verbose = FALSE,
                             seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("splatter", quietly = TRUE)){
    cat("Splatter is not installed on your device\n")
    cat("Installing splatter...\n")
    BiocManager::install("splatter")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  assertthat::assert_that(class(parameters) == "SplatParams")
  # nCells
  if(!is.null(other_prior[["nCells"]])){
    parameters <- splatter::setParam(parameters, name = "nCells", value = other_prior[["nCells"]])
  }
  # nGenes
  if(!is.null(other_prior[["nGenes"]])){
    parameters <- splatter::setParam(parameters, name = "nGenes", value = other_prior[["nGenes"]])
  }
  # nGroup
  if(!is.null(other_prior[["group.condition"]])){
    parameters <- splatter::setParam(parameters,
                                     name = "nGroups",
                                     value = length(unique(other_prior[["group.condition"]])))
  }else{
    if(!is.null(other_prior[["paths"]])){
      if(other_prior[["paths"]]){
        tree <- simutils::make_trees(ref_data = ref_data,
                                     group = NULL,
                                     is_Newick = FALSE,
                                     is_parenthetic = TRUE,
                                     return_group = TRUE)
        group <- tree[["group"]]
      }
    }
  }
  if(!is.null(other_prior[["prob.group"]])){
    parameters <- splatter::setParam(parameters,
                                     name = "group.prob",
                                     value = other_prior[["prob.group"]])

  }else{
    nGroups <- length(unique(group))
    prob.group <- c(rep(1/nGroups, nGroups-1),
                    1 - c(1/nGroups * c(nGroups-1)))
    parameters <- splatter::setParam(parameters,
                                     name = "group.prob",
                                     value = prob.group)
  }

  # Get params to check
  params_check <- splatter::getParams(parameters, c("nBatches",
                                                    "batchCells",
                                                    "nGroups",
                                                    "group.prob",
                                                    "de.prob",
                                                    "nCells",
                                                    "nGenes"))

  # check batches
  if(length(params_check[["batchCells"]]) > 1){
    assertthat::assert_that(params_check[["nBatches"]] > 1)
  }else{
    assertthat::assert_that(params_check[["nBatches"]] == 1)
  }
  # check groups
  if(length(params_check[["group.prob"]]) > 1){
    assertthat::assert_that(params_check[["nGroups"]] > 1)
  }else{
    assertthat::assert_that(params_check[["nGroups"]] == 1)
  }

  # DEGs proportion
  de.prob <- params_check[["de.prob"]]
  # Return to users
  cat(glue::glue("nCells: {params_check[['nCells']]}"), "\n")
  cat(glue::glue("nGenes: {params_check[['nGenes']]}"), "\n")
  cat(glue::glue("nGroups: {params_check[['nGroups']]}"), "\n")
  cat(glue::glue("de.prob: {de.prob}"), "\n")
  cat(glue::glue("nBatches: {params_check[['nBatches']]}"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using Splat\n")
  }
  # Seed
  parameters <- splatter::setParam(parameters, name = "seed", value = seed)
  # Estimation
  tryCatch({
    if(!is.null(other_prior[["paths"]])){
      cat("Simulating trajectory datasets by Splat")
      submethod <- "paths"
      parameters <- splatter::setParam(parameters,
                                       name = "path.from",
                                       value = seq(1:nGroups)-1)
    }else{
      if(params_check[["nGroups"]] == 1){
        submethod <- "single"
      }else if(params_check[["nGroups"]] != 1){
        submethod <- "groups"
      }
    }
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- splatter::splatSimulate(parameters,
                                                 method = submethod,
                                                 verbose = verbose))
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

