#' Estimate Parameters From Real Datasets by POWSC
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using `Est2Phase` function in POWSC package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
POWSC_estimation <- function(ref_data,
                             verbose = FALSE,
                             other_prior,
                             seed
){
  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("POWSC", quietly = TRUE)){
    message("Splatter is not installed on your device...")
    message("Installing POWSC...")
    BiocManager::install("POWSC")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  if(is.null(other_prior[["low.prob"]])){
    low.prob <- 0.99
  }else{
    low.prob <- other_prior[["low.prob"]]
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    message("Estimating parameters using POWSC")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- POWSC::Est2Phase(ref_data, low.prob = low.prob)
    )
  }, error = function(e){
    print(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}



#' Simulate Datasets by POWSC
#'
#' This function is used to simulate datasets from learned parameters by `Simulate2SCE`
#' function in POWSC package.
#'
#' @param parameters A object generated by [POWSC::Est2Phase()]
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternative choices: list, SingleCellExperiment,
#' Seurat, h5ad. If you select `h5ad`, you will get a path where the .h5ad file saves to.
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom glue glue
#' @importFrom SingleCellExperiment counts colData rowData
#' @importFrom Seurat as.Seurat
#' @importFrom stringr str_replace
#'
#' @export
#'
POWSC_simulation <- function(parameters,
                             other_prior,
                             return_format,
                             verbose = FALSE,
                             seed
){
  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("POWSC", quietly = TRUE)){
    message("Splatter is not installed on your device...")
    message("Installing POWSC...")
    BiocManager::install("POWSC")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(is.null(other_prior[["nCells"]])){
    n <- ncol(parameters[["exprs"]])
  }else{
    n <- other_prior[["nCells"]]
  }
  if(is.null(other_prior[["de.prob"]])){
    perDE <- 0.05
  }else{
    perDE <- other_prior[["de.prob"]]
  }
  message(glue::glue("nCells: {n}"))
  message(glue::glue("nGenes: {dim(parameters[['exprs']])[1]}"))
  message(glue::glue("nGroups: 2"))
  message(glue::glue("de.prob: {perDE}"))
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    message("Simulating datasets using POWSC")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- POWSC::Simulate2SCE(n = n,
                                             perDE = perDE,
                                             estParas1 = parameters,
                                             estParas2 = parameters))
  }, error = function(e){
    print(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  counts <- SingleCellExperiment::counts(simulate_result[["sce"]])
  colnames(counts) <- paste0("Cell", c(1:ncol(counts)))
  rownames(counts) <- paste0("Gene", c(1:nrow(counts)))
  col_data <- data.frame("cell_name" = colnames(counts),
                         "group" = ifelse(colData(simulate_result[["sce"]])[,1] == "celltype1", "Group1", "Group2"))
  row_data <- data.frame("gene_name" = rownames(counts))
  simulate_result <- simulate_result[["sce"]]
  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

