#' Estimate Parameters From Real Datasets by POWSC
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{Est2Phase} function in POWSC package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom POWSC Est2Phase
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
POWSC_estimation <- function(ref_data, verbose = FALSE, other_prior, seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("POWSC", quietly = TRUE)){
    cat("Splatter is not installed on your device\n")
    cat("Installing POWSC...\n")
    BiocManager::install("POWSC")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  if(is.null(other_prior[["low.prob"]])){
    low.prob <- 0.99
  }else{
    low.prob <- other_prior[["low.prob"]]
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using POWSC\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- POWSC::Est2Phase(ref_data, low.prob = low.prob)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by POWSC
#'
#' @param parameters A object generated by \code{\link[POWSC]{Est2Phase}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom POWSC Simulate2SCE
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#' @importFrom SingleCellExperiment counts colData rowData
#' @importFrom Seurat as.Seurat
#' @importFrom SeuratDisk SaveH5Seurat Convert
#' @importFrom stringr str_replace
#'
#' @export
#'
POWSC_simulation <- function(parameters,
                             other_prior,
                             return_format,
                             verbose = FALSE,
                             seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("POWSC", quietly = TRUE)){
    cat("Splatter is not installed on your device\n")
    cat("Installing POWSC...\n")
    BiocManager::install("POWSC")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  cat("When you are using POWSC, you can not set the number of genes. This number depends on the genes of real data.")
  if(is.null(other_prior[["nCells"]])){
    n <- ncol(parameters[["exprs"]])
  }else{
    n <- other_prior[["nCells"]]
  }
  if(is.null(other_prior[["de.prob"]])){
    perDE <- 0.05
  }else{
    perDE <- other_prior[["de.prob"]]
  }

  cat(glue::glue("nCells: {n}"), "\n")
  cat(glue::glue("nGenes: {dim(parameters[['exprs']])[1]}"), "\n")
  cat(glue::glue("nGroups: 2"), "\n")
  cat(glue::glue("de.prob: {perDE}"), "\n")

  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using POWSC\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- POWSC::Simulate2SCE(n = n,
                                             perDE = perDE,
                                             estParas1 = parameters,
                                             estParas2 = parameters))
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  counts <- SingleCellExperiment::counts(simulate_result[["sce"]])
  colnames(counts) <- paste0("Cell", c(1:ncol(counts)))
  rownames(counts) <- paste0("Gene", c(1:nrow(counts)))

  col_data <- data.frame("cell_name" = colnames(counts),
                         "group" = ifelse(colData(simulate_result[["sce"]])[,1] == "celltype1", "Group1", "Group2"))

  row_data_tmp <- data.frame("gene_name" = stringr::str_replace_all(names(simulate_result[["pi.df"]]), "_", ""),
                             "de_fc" = simulate_result[["lfc"]],
                             "number" = as.numeric(stringr::str_replace_all(names(simulate_result[["pi.df"]]), "Gene_", "")))

  row_data <- data.frame("gene_name" = rownames(counts),
                         "de_genes" = ifelse(simulate_result[["DESetup"]][["pLFC"]][[1]] == 0, FALSE, TRUE),
                         "de_fc" = simulate_result[["DESetup"]][["pLFC"]][[1]])

  simulate_result <- simulate_result[["sce"]]

  if(return_format == "SingleCellExperiment"){
    simulate_result <- simulate_result
  }
  if(return_format == "list"){
    count_data <- SingleCellExperiment::counts(simulate_result)
    col_meta <- as.data.frame(SingleCellExperiment::colData(simulate_result))
    row_meta <- as.data.frame(SingleCellExperiment::rowData(simulate_result))
    simulate_result <- dplyr::lst(count_data,
                                  col_meta,
                                  row_meta)
  }
  if(return_format == "Seurat"){
    simulate_result <- Seurat::as.Seurat(simulate_result,
                                         counts = "counts",
                                         data = NULL)
  }
  if(return_format == "h5ad"){
    # Convert to Seurat object
    simulate_result <- Seurat::as.Seurat(simulate_result,
                                         counts = "counts",
                                         data = NULL)
    # Tmp file
    tmp_path <- tempdir()
    data_save_name <- file.path(tmp_path, paste0(time_string(), ".h5Seurat")) %>%
      simutils::fix_path()
    SeuratDisk::SaveH5Seurat(simulate_result, filename = data_save_name)
    SeuratDisk::Convert(data_save_name, dest = "h5ad")

    # data path
    data_path <- stringr::str_replace(data_save_name,
                                      pattern = "h5Seurat",
                                      replacement = "h5ad")
    cat(glue::glue("Your data has been save to {data_path}", "\n"))
    simulate_result <- list(file_type = "h5ad",
                            save_path = data_path)
  }

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

