#' Estimate Parameters From Real Datasets by scDesign2
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{fit_model_scDesign2} function in scDesign2 package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom scDesign2 fit_model_scDesign2
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
scDesign2_estimation <- function(ref_data,
                                 verbose = FALSE,
                                 other_prior,
                                 seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("scDesign2", quietly = TRUE)){
    cat("scDesign2 is not installed on your device\n")
    cat("Installing scDesign2...\n")
    devtools::install_github("JSB-UCLA/scDesign2")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }

  if(is.null(other_prior[["cell_type_sel"]])){
    colnames(ref_data) <- rep("A", ncol(ref_data))
    other_prior[["cell_type_sel"]] <- "A"
  }else{
    colnames(ref_data) <- rep(other_prior[["cell_type_sel"]], ncol(ref_data))
  }
  other_prior[["data_mat"]] <- ref_data

  if(is.null(other_prior[["sim_method"]])){
    other_prior[["sim_method"]] <- "copula"
  }
  if(is.null(other_prior[["marginal"]])){
    other_prior[["marginal"]] <- "auto_choose"
  }

  estimate_formals <- as.list(formals(scDesign2::fit_model_scDesign2))
  for(param in names(estimate_formals)){
    names_wait_check <- names(other_prior)
    if(param %in% names_wait_check){
      estimate_formals[[param]] <- other_prior[[param]]
    }
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using scDesign2\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- do.call(scDesign2::fit_model_scDesign2, estimate_formals)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by scDesign2
#'
#' @param parameters A object generated by \code{\link[scDesign2]{fit_model_scDesign2}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom scDesign2 simulate_count_scDesign2
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#' @importFrom SingleCellExperiment counts colData rowData SingleCellExperiment
#' @importFrom Seurat as.Seurat
#' @importFrom SeuratDisk SaveH5Seurat Convert
#' @importFrom stringr str_extract
#' @importFrom dplyr mutate case_when
#'
#' @export
#'
scDesign2_simulation <- function(parameters,
                                 other_prior,
                                 return_format,
                                 verbose = FALSE,
                                 seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("scDesign2", quietly = TRUE)){
    cat("scDesign2 is not installed on your device\n")
    cat("Installing scDesign2\n")
    devtools::install_github("JSB-UCLA/scDesign2")
  }

  other_prior[["model_params"]] <- parameters
  other_prior[["n_cell_new"]] <- parameters[[1]][["n_cell"]]

  if(is.null(other_prior[["sim_method"]])){
    other_prior[["sim_method"]] <- "copula"
  }
  if(is.null(other_prior[["reseq_method"]])){
    other_prior[["reseq_method"]] <- "mean_scale"
  }

  simulate_formals <- as.list(formals(scDesign2::simulate_count_scDesign2))
  for(param in names(simulate_formals)){
    names_wait_check <- names(other_prior)
    if(param %in% names_wait_check){
      simulate_formals[[param]] <- other_prior[[param]]
    }
  }

  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  # Return to users
  cat(glue::glue("Your simulated datasets will have {parameters[[1]][['n_cell']]} cells, {nrow(parameters[[1]][['marginal_param1']])+nrow(parameters[[1]][['marginal_param2']])} genes"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using scDesign2\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- do.call(scDesign2::simulate_count_scDesign2, simulate_formals)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  counts <- simulate_result
  # Rename
  rownames(counts) <- paste0("Gene", 1:nrow(counts))
  colnames(counts) <- paste0("Cell", 1:ncol(counts))

  # col_data
  col_data <- data.frame("cell_name" = colnames(counts))
  # Row data
  row_data <- data.frame("gene_name" = rownames(counts))

  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)
  if(return_format == "SingleCellExperiment"){
    simulate_result <- simulate_result
  }
  if(return_format == "list"){
    count_data <- SingleCellExperiment::counts(simulate_result)
    col_meta <- as.data.frame(SingleCellExperiment::colData(simulate_result))
    row_meta <- as.data.frame(SingleCellExperiment::rowData(simulate_result))
    simulate_result <- dplyr::lst(count_data,
                                  col_meta,
                                  row_meta)
  }
  if(return_format == "Seurat"){
    simulate_result <- Seurat::as.Seurat(simulate_result,
                                         counts = "counts",
                                         data = NULL)
  }
  if(return_format == "h5ad"){
    # Convert to Seurat object
    simulate_result <- Seurat::as.Seurat(simulate_result,
                                         counts = "counts",
                                         data = NULL)
    # Tmp file
    tmp_path <- tempdir()
    data_save_name <- file.path(tmp_path, paste0(time_string(), ".h5Seurat")) %>%
      simutils::fix_path()
    SeuratDisk::SaveH5Seurat(simulate_result, filename = data_save_name)
    SeuratDisk::Convert(data_save_name, dest = "h5ad")

    # data path
    data_path <- stringr::str_replace(data_save_name,
                                      pattern = "h5Seurat",
                                      replacement = "h5ad")
    cat(glue::glue("Your data has been save to {data_path}", "\n"))
    simulate_result <- list(file_type = "h5ad",
                            save_path = data_path)
  }

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

