#' Estimate Parameters From Real Datasets by zingeR
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{getDatasetZTNB} function in zingeR package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs are usually customed, so before simulating a dataset you must point it out.
#' See `Details` below for more information.
#' @param seed An integer of a random seed.
#' @importFrom zingeR getDatasetZTNB
#' @importFrom stats model.matrix
#' @import gamlss.dist gamlss.tr
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#' @details
#' When you use zingeR to estimate parameters from a real dataset, you must input
#' a numeric vector to specify the groups that each cell belongs to, like
#' `other_prior = list(group.condition = the numeric vector)`. See `Examples`
#' and learn from it.
#' @references
#' Github URL: <https://github.com/statOmics/zingeR>
#' @examples
#' ref_data <- simmethods::data
#' group_condition <- as.numeric(simmethods::group_condition)
#'
#' estimate_result <- simmethods::zingeR_estimation(ref_data = ref_data,
#'                                                  other_prior = list(group.condition = group_condition),
#'                                                  verbose = TRUE,
#'                                                  seed = 111)
zingeR_estimation <- function(ref_data,
                              verbose = FALSE,
                              other_prior,
                              seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("zingeR", quietly = TRUE)){
    cat("zingeR is not installed on your device\n")
    cat("Installing zingeR...\n")
    devtools::install_github("statOmics/zingeR")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  ## Filter
  other_prior[["counts"]] <- ref_data[apply(ref_data, 1, function(x) length(x[x>0])) > 1, ]
  if(is.null(other_prior[["group.condition"]])){
    stop("Please input condition information that each cell belongs to.")
  }
  other_prior[["design"]] <- stats::model.matrix(~as.factor(other_prior[["group.condition"]]))

  estimate_formals <- simutils::change_parameters(function_expr = "zingeR::getDatasetZTNB",
                                                  other_prior = other_prior,
                                                  step = "estimation")

  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using zingeR\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- zingeR::getDatasetZTNB(counts = estimate_formals[["counts"]],
                                                design = estimate_formals[["design"]],
                                                drop.extreme.dispersion = estimate_formals[["drop.extreme.dispersion"]],
                                                offset = estimate_formals[["offset"]])
    )
  }, error = function(e){
    as.character(e)
  })

  if(length(estimate_result[["dataset.AveLogCPM"]]) == 0){
    stop("Your data estimation failed, please change it.")
  }

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by zingeR
#'
#' @param ref_data A matrix for one dataset or a list of datasets with their own
#' names. This is usually unused except for some methods, e.g. SCRIP, scDesign,
#' zingeR.
#' @param parameters A object generated by [zingeR::getDatasetZTNB()]
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs are usually customed, so before simulating a dataset you must point it out.
#' See `Details` below for more information.
#' @param return_format A character. Alternative choices: list, SingleCellExperiment,
#' Seurat, h5ad. If you select `h5ad`, you will get a path where the .h5ad file saves to.
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#' @importFrom zingeR NBsimSingleCell
#' @export
#' @details
#' In addtion to simulate datasets with default parameters, users want to simulate
#' other kinds of datasets, e.g. a counts matrix with 2 or more cell groups. In
#' zingeR, you can set extra parameters to simulate datasets.
#'
#' The customed parameters you can set are below:
#' 1. nCells. In zingeR, You can directly set `other_prior = list(nCells = 5000)` to simulate 5000 cells. nCells must be larger than the reference data.
#' 2. nGenes. You can directly set `other_prior = list(nGenes = 5000)` to simulate 5000 genes. nGenes must be larger than the reference data.
#' 3. de.prob. You can directly set `other_prior = list(de.prob = 0.2)` to simulate DEGs that account for 20 percent of all genes.
#' 4. fc.group. You can directly set `other_prior = list(fc.group = 2)` to specify the fold change of DEGs.
#'
#' For more customed parameters in zingeR, please check [zingeR::NBsimSingleCell()].
#' @references
#' Github URL: <https://github.com/statOmics/zingeR>
#' @examples
#' ref_data <- simmethods::data
#' group_condition <- as.numeric(simmethods::group_condition)
#'
#' estimate_result <- simmethods::zingeR_estimation(ref_data = ref_data,
#'                                                  other_prior = list(group.condition = group_condition),
#'                                                  verbose = TRUE,
#'                                                  seed = 111)
#'
#' ## Default parameters
#' simulate_result <- simmethods::zingeR_simulation(ref_data = ref_data,
#'                                                  other_prior = list(group.condition = group_condition),
#'                                                  parameters = estimate_result[["estimate_result"]],
#'                                                  return_format = "list",
#'                                                  verbose = TRUE,
#'                                                  seed = 111)
#' ## counts
#' counts <- simulate_result[["simulate_result"]][["count_data"]]
#' dim(counts)
#' ## cell information
#' col_data <- simulate_result[["simulate_result"]][["col_meta"]]
#' ## gene information
#' row_data <- simulate_result[["simulate_result"]][["row_meta"]]
#' head(row_data)
#'
#'
#' ## In zingeR, users can only set the number of cells and genes which is higher
#' ## than the reference data. In addtion, the proportion of DEGs and fold change are
#' ## able to be customed. Not that zingeR dose not return cell group information.
#' ## Default parameters
#' simulate_result <- simmethods::zingeR_simulation(ref_data = ref_data,
#'                                                  other_prior = list(group.condition = group_condition,
#'                                                                     nCells = 1000,
#'                                                                     nGenes = 5000,
#'                                                                     de.prob = 0.2,
#'                                                                     fc.group = 4),
#'                                                  parameters = estimate_result[["estimate_result"]],
#'                                                  return_format = "list",
#'                                                  verbose = TRUE,
#'                                                  seed = 111)
#' ## counts
#' counts <- simulate_result[["simulate_result"]][["count_data"]]
#' dim(counts)
#' ## cell information
#' col_data <- simulate_result[["simulate_result"]][["col_meta"]]
#' ## gene information
#' row_data <- simulate_result[["simulate_result"]][["row_meta"]]
#' head(row_data)
zingeR_simulation <- function(ref_data = NULL,
                              parameters,
                              other_prior = NULL,
                              return_format,
                              verbose = FALSE,
                              seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("zingeR", quietly = TRUE)){
    cat("zingeR is not installed on your device\n")
    cat("Installing zingeR...\n")
    devtools::install_github("statOmics/zingeR")
  }
  if(is.null(ref_data)){
    stop("Please input ref_data when using zingeR to simulate datasets")
  }
  other_prior[["dataset"]] <- ref_data[apply(ref_data, 1, function(x) length(x[x>0])) > 1, ]
  other_prior[["params"]] <- parameters
  ## group.condition
  if(is.null(other_prior[["group.condition"]])){
    stop("Please input condition information that each cell belongs to.")
  }else{
    other_prior[["group"]] <- other_prior[["group.condition"]]-1
  }
  ## gene number
  if(is.null(other_prior[["nGenes"]])){
    other_prior[["nTags"]] <- nrow(ref_data)
  }else{
    other_prior[["nTags"]] <- other_prior[["nGenes"]]
  }
  ## nCells
  ## gene number
  if(is.null(other_prior[["nCells"]])){
    other_prior[["nlibs"]] <- length(other_prior[["group"]])
  }else{
    other_prior[["nlibs"]] <- other_prior[["nCells"]]
  }
  ## ind
  if(is.null(other_prior[["ind"]])){
    if(is.null(other_prior[["de.prob"]])){
      other_prior[["de.prob"]] <- 0.1
    }
    set.seed(seed)
    ind <- sample(1:nrow(ref_data),
                  floor(other_prior[["nTags"]]*other_prior[["de.prob"]]),
                  replace = FALSE)
    other_prior[["ind"]] <- ind
  }
  ## fc
  if(is.null(other_prior[["fc.group"]])){
    if(!is.null(other_prior[["ind"]])){
      other_prior[["foldDiff"]] <- rep(2, length(other_prior[["ind"]]))
    }
  }else{
    other_prior[["foldDiff"]] <- rep(other_prior[["fc.group"]], length(other_prior[["ind"]]))
  }
  ## lib.size
  if(is.null(other_prior[["lib.size"]])){
    other_prior[["lib.size"]] <- NULL
  }

  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################

  simulate_formals <- simutils::change_parameters(function_expr = "zingeR::NBsimSingleCell",
                                                  other_prior = other_prior,
                                                  step = "simulation")
  # Return to users
  cat(glue::glue("nCells: {simulate_formals[['nlibs']]}"), "\n")
  cat(glue::glue("nGenes: {simulate_formals[['nTags']]}"), "\n")
  cat(glue::glue("nGroups: {length(unique(other_prior[['group']]))}"), "\n")
  cat(glue::glue("prob.group: {other_prior[['de.prob']]}"), "\n")
  cat(glue::glue("fc.group: {unique(simulate_formals[['foldDiff']])}"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using zingeR\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
    simulate_result <- do.call(zingeR::NBsimSingleCell, simulate_formals))
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  ## counts
  counts <- simulate_result[["counts"]]
  colnames(counts) <- paste0("Cell", 1:ncol(counts))
  rownames(counts) <- paste0("Gene", 1:nrow(counts))
  ## col_data
  col_data <- data.frame("cell_name" = colnames(counts))
  ## row_data
  indDE <- simulate_result[["indDE"]]
  names(indDE) <- rep("DE", length(indDE))
  indNonDE <- simulate_result[["indNonDE"]]
  names(indNonDE) <- rep("non-DE", length(indNonDE))
  gene_DE <- sort(c(indDE, indNonDE))
  row_data <- data.frame("gene_name" = rownames(counts),
                         "de_genes" = ifelse(names(gene_DE) == "DE", TRUE, FALSE),
                         "de_fc" = 0)
  row_data[indDE, 3] <- simulate_result[["foldDiff"]]
  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)

  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

