#' Estimate Parameters From Real Datasets by zingeR
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{getDatasetZTNB} function in zingeR package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom zingeR getDatasetZTNB
#' @importFrom stats model.matrix
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
zingeR_estimation <- function(ref_data,
                              verbose = FALSE,
                              other_prior,
                              seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("zingeR", quietly = TRUE)){
    cat("zingeR is not installed on your device\n")
    cat("Installing zingeR...\n")
    devtools::install_github("statOmics/zingeR")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }

  ## Filter
  ref_data <- ref_data[apply(ref_data, 1, function(x) length(x[x>0])) > 1, ]

  other_prior[["counts"]] <- ref_data

  if(is.null(other_prior[["condition"]])){
    stop("Please input condition information that each cell belongs to.")
  }
  other_prior[["design"]] <- stats::model.matrix(~as.factor(other_prior[["condition"]]))

  estimate_formals <- simutils::change_parameters(function_expr = "zingeR::getDatasetZTNB",
                                                  other_prior = other_prior,
                                                  step = "estimation")

  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using zingeR\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- zingeR::getDatasetZTNB(counts = estimate_formals[["counts"]],
                                                design = estimate_formals[["design"]],
                                                drop.extreme.dispersion = estimate_formals[["drop.extreme.dispersion"]],
                                                offset = estimate_formals[["offset"]])
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by zingeR
#'
#' @param ref_data A matrix for one dataset or a list of datasets with their own
#' names. This is usually unused except for some methods, e.g. SCRIP, scDesign,
#' zingeR.
#' @param parameters A object generated by \code{\link[zingeR]{NBsimSingleCell}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom zingeR NBsimSingleCell
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#' @importFrom SingleCellExperiment counts colData rowData
#'
#' @export
#'
zingeR_simulation <- function(ref_data,
                              parameters,
                              other_prior,
                              return_format,
                              verbose = FALSE,
                              seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("zingeR", quietly = TRUE)){
    cat("zingeR is not installed on your device\n")
    cat("Installing zingeR...\n")
    devtools::install_github("statOmics/zingeR")
  }
  other_prior[["dataset"]] <- ref_data[apply(ref_data, 1, function(x) length(x[x>0])) > 1, ]
  other_prior[["params"]] <- parameters
  ## condition
  if(is.null(other_prior[["condition"]])){
    stop("Please input condition information that each cell belongs to.")
  }else{
    other_prior[["group"]] <- other_prior[["condition"]]-1
  }
  ## gene number
  if(is.null(other_prior[["nGenes"]])){
    other_prior[["nTags"]] <- nrow(ref_data)
  }
  ## ind
  if(is.null(other_prior[["ind"]])){
    if(!is.null(other_prior[["prob.group"]])){
    }else{
      other_prior[["prob.group"]] <- 0.1
    }
    set.seed(seed)
    ind <- sample(1:nrow(ref_data),
                  floor(other_prior[["nTags"]]*other_prior[["prob.group"]]),
                  replace = FALSE)
    other_prior[["ind"]] <- ind
  }
  ## fc
  if(is.null(other_prior[["fc.group"]])){
    if(!is.null(other_prior[["ind"]])){
      other_prior[["foldDiff"]] <- rep(3, length(other_prior[["ind"]]))
    }else{
      other_prior[["foldDiff"]] <- 3
    }
  }else{
    other_prior[["foldDiff"]] <- other_prior[["fc.group"]]
  }
  ## lib.size
  if(is.null(other_prior[["lib.size"]])){
    set.seed(seed)
    lib.size <- sample(colSums(ref_data), ncol(ref_data), replace=TRUE)
    other_prior[["lib.size"]] <- lib.size
  }
  ## nlibs
  if(is.null(other_prior[["nlibs"]])){
    other_prior[["nlibs"]] <- length(other_prior[["group"]])
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################

  simulate_formals <- simutils::change_parameters(function_expr = "zingeR::NBsimSingleCell",
                                                  other_prior = other_prior,
                                                  step = "simulation")
  # Return to users
  cat(glue::glue("nCells: {ncol(simulate_formals[['dataset']])}"), "\n")
  cat(glue::glue("nGenes: {nrow(simulate_formals[['dataset']])}"), "\n")
  cat(glue::glue("prob.group: {other_prior[['prob.group']]}"), "\n")
  cat(glue::glue("fc.group: {unique(simulate_formals[['foldDiff']])}"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using zingeR\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
    simulate_result <- do.call(zingeR::NBsimSingleCell, simulate_formals))
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  ## counts
  counts <- simulate_result[["counts"]]
  colnames(counts) <- paste0("Cell", 1:ncol(counts))
  rownames(counts) <- paste0("Gene", 1:nrow(counts))
  ## col_data
  col_data <- data.frame("cell_name" = colnames(counts),
                         "group" = paste0("Group", as.numeric(simulate_result[["group"]])))
  ## row_data
  indDE <- simulate_result[["indDE"]]
  names(indDE) <- rep("DE", length(indDE))
  indNonDE <- simulate_result[["indNonDE"]]
  names(indNonDE) <- rep("non-DE", length(indNonDE))
  gene_DE <- sort(c(indDE, indNonDE))
  row_data <- data.frame("gene_name" = rownames(counts),
                         "de_genes" = ifelse(names(gene_DE) == "DE", TRUE, FALSE),
                         "fc" = 0)
  row_data[indDE, 3] <- simulate_result[["foldDiff"]]
  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)

  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

