#' Estimate Parameters From Real Datasets by zinbwaveZinger
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{getDatasetMoMPositive} function in zinbwaveZingercollected package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom zinbwaveZingercollected getDatasetMoMPositive
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
zinbwaveZinger_estimation <- function(ref_data,
                                      verbose = FALSE,
                                      other_prior,
                                      seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("zinbwaveZingercollected", quietly = TRUE)){
    cat("zinbwaveZinger is not installed on your device\n")
    cat("Installing zinbwaveZinger...\n")
    devtools::install_github("duohongrui/zinbwaveZingercollected")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  ## Filter
  other_prior[["counts"]] <- ref_data[apply(ref_data, 1, function(x) length(x[x>0])) > 1, ]
  estimate_formals <- simutils::change_parameters(function_expr = "zinbwaveZingercollected::getDatasetMoMPositive",
                                                  other_prior = other_prior,
                                                  step = "estimation")

  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using zinbwaveZinger\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- do.call(zinbwaveZingercollected::getDatasetMoMPositive, estimate_formals)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by zingeR
#'
#' @param ref_data A matrix for one dataset or a list of datasets with their own
#' names. This is usually unused except for some methods, e.g. SCRIP, scDesign,
#' zingeR, zinbwaveZinger.
#' @param parameters A object generated by \code{\link[zinbwaveZingercollected]{NBsimSingleCell_zinbwaveZinger}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom zinbwaveZingercollected NBsimSingleCell_zinbwaveZinger
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#' @importFrom SingleCellExperiment counts colData rowData
#'
#' @export
#'
zinbwaveZinger_simulation <- function(ref_data,
                                      parameters,
                                      other_prior,
                                      return_format,
                                      verbose = FALSE,
                                      seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("zinbwaveZingercollected", quietly = TRUE)){
    cat("zinbwaveZinger is not installed on your device\n")
    cat("Installing zinbwaveZinger...\n")
    devtools::install_github("duohongrui/zinbwaveZingercollected")
  }
  other_prior[["dataset"]] <- ref_data[apply(ref_data, 1, function(x) length(x[x>0])) > 1, ]
  other_prior[["params"]] <- parameters
  ## condition
  if(is.null(other_prior[["group.condition"]])){
    stop("Please input condition information that each cell belongs to.")
  }else{
    other_prior[["group"]] <- other_prior[["group.condition"]]-1
  }
  ## gene number
  if(is.null(other_prior[["nGenes"]])){
    other_prior[["nTags"]] <- nrow(ref_data)
  }else{
    other_prior[["nTags"]] <- other_prior[["nGenes"]]
  }
  ## nCells
  if(is.null(other_prior[["nCells"]])){
    other_prior[["nlibs"]] <- ncol(ref_data)
  }else{
    other_prior[["nlibs"]] <- other_prior[["nCells"]]
  }
  ## ind
  if(is.null(other_prior[["ind"]])){
    if(is.null(other_prior[["de.prob"]])){
      other_prior[["de.prob"]] <- 0.1
    }
    set.seed(seed)
    ind <- sample(1:nrow(ref_data),
                  floor(other_prior[["nTags"]]*other_prior[["de.prob"]]),
                  replace = FALSE)
    other_prior[["ind"]] <- ind
  }
  ## fc
  if(is.null(other_prior[["fc.group"]])){
    if(!is.null(other_prior[["ind"]])){
      other_prior[["foldDiff"]] <- rep(3, length(other_prior[["ind"]]))
    }
  }else{
    other_prior[["foldDiff"]] <- other_prior[["fc.group"]]
  }
  ## lib.size
  if(is.null(other_prior[["lib.size"]])){
    other_prior[["lib.size"]] <- NULL
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################

  simulate_formals <- simutils::change_parameters(function_expr = "zinbwaveZingercollected::NBsimSingleCell_zinbwaveZinger",
                                                  other_prior = other_prior,
                                                  step = "simulation")
  # Return to users
  cat(glue::glue("nCells: {simulate_formals[['nlibs']]}"), "\n")
  cat(glue::glue("nGenes: {simulate_formals[['nTags']]}"), "\n")
  cat(glue::glue("prob.group: {other_prior[['de.prob']]}"), "\n")
  cat(glue::glue("fc.group: {unique(simulate_formals[['foldDiff']])}"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using zinbwaveZinger\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- do.call(zinbwaveZingercollected::NBsimSingleCell_zinbwaveZinger, simulate_formals))
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  ## counts
  counts <- simulate_result[["counts"]]
  colnames(counts) <- paste0("Cell", 1:ncol(counts))
  rownames(counts) <- paste0("Gene", 1:nrow(counts))
  ## col_data
  col_data <- data.frame("cell_name" = colnames(counts),
                         "group" = paste0("Group", as.numeric(simulate_result[["group"]])))
  ## row_data
  indDE <- simulate_result[["indDE"]]
  names(indDE) <- rep("DE", length(indDE))
  indNonDE <- simulate_result[["indNonDE"]]
  names(indNonDE) <- rep("non-DE", length(indNonDE))
  gene_DE <- sort(c(indDE, indNonDE))
  row_data <- data.frame("gene_name" = rownames(counts),
                         "de_genes" = ifelse(names(gene_DE) == "DE", TRUE, FALSE),
                         "fc" = 0)
  row_data[indDE, 3] <- simulate_result[["foldDiff"]]
  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)

  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

