#' Estimate Parameters From Real Datasets by BASiCS
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{BASiCSEstimate} function in Splatter package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param seed An integer of a random seed.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @importFrom peakRAM peakRAM
#' @importFrom splatter BASiCSEstimate
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
BASiCS_estimation <- function(ref_data,
                              verbose = FALSE,
                              other_prior,
                              seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("splatter", quietly = TRUE)){
    cat("Splatter is not installed on your device\n")
    cat("Installing splatter...\n")
    BiocManager::install("splatter")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  other_prior[["counts"]] <- ref_data
  other_prior[["params"]] <- splatter::newBASiCSParams()
  if(is.null(other_prior[["spike.info"]]) & is.null(other_prior[["batch.condition"]])){
    stop("At least one of spike.info and batch must be provided.")
  }
  if(!is.null(other_prior[["batch.condition"]])){
    other_prior[["batch"]] <- other_prior[["batch.condition"]]
  }
  estimate_formals <- simutils::change_parameters(function_expr = "splatter::BASiCSEstimate",
                                                  other_prior = other_prior,
                                                  step = "estimation")
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using BASiCS\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- splatter::BASiCSEstimate(counts = estimate_formals[["counts"]],
                                                  batch = estimate_formals[["batch"]],
                                                  spike.info = estimate_formals[["spike.info"]],
                                                  n = estimate_formals[["n"]],
                                                  thin = estimate_formals[["thin"]],
                                                  burn = estimate_formals[["burn"]],
                                                  regression = estimate_formals[["regression"]],
                                                  params = estimate_formals[["params"]],
                                                  verbose = estimate_formals[["verbose"]],
                                                  progress = estimate_formals[["progress"]])
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by BASiCS
#'
#' @param parameters A object generated by \code{\link[splatter]{BASiCSEstimate}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom splatter getParams setParam BASiCSSimulate
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#' @importFrom SingleCellExperiment counts colData rowData
#'
#' @export
#'
BASiCS_simulation <- function(parameters,
                              other_prior,
                              return_format,
                              verbose = FALSE,
                              seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("splatter", quietly = TRUE)){
    cat("Splatter is not installed on your device\n")
    cat("Installing splatter...\n")
    BiocManager::install("splatter")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  assertthat::assert_that(class(parameters) == "BASiCSParams")

  # Get params to check
  params_check <- splatter::getParams(parameters, c("nCells",
                                                    "nGenes",
                                                    "nBatches"))
  # Return to users
  cat(glue::glue("Your simulated datasets will have {params_check[['nCells']]} cells, {params_check[['nGenes']]} genes, {params_check[['nBatches']]} batches(s)"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using BASiCS\n")
  }
  # Seed
  parameters <- splatter::setParam(parameters, name = "seed", value = seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- splatter::BASiCSSimulate(parameters, verbose = verbose)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

