#' Estimate Parameters From Real Datasets by SPARSim
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{SPARSim_estimate_parameter_from_data} function in SPARSim package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom SPARSim SPARSim_estimate_parameter_from_data scran_normalization
#' @importFrom stats model.matrix
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
SPARSim_estimation <- function(ref_data,
                               verbose = FALSE,
                               other_prior,
                               seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("SPARSim", quietly = TRUE)){
    cat("SPARSim is not installed on your device\n")
    cat("Installing SPARSim...\n")
    devtools::install_gitlab("sysbiobig/sparsim")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  other_prior[["raw_data"]] <- ref_data
  other_prior[["norm_data"]] <- SPARSim::scran_normalization(ref_data)

  if(is.null(other_prior[["condition"]])){
    count_matrix_conditions <- list(conditionA = 1:ncol(ref_data))
    other_prior[["conditions"]] <- count_matrix_conditions
  }else{
    count_matrix_conditions <- list()
    condition_length <- length(unique(other_prior[["condition"]]))
    for(i in 1:condition_length){
      index <- which(other_prior[["condition"]] == i)
      count_matrix_conditions[[paste0("cond_", LETTERS[i])]] <- index
    }
    other_prior[["conditions"]] <- count_matrix_conditions
  }

  estimate_formals <- simutils::change_parameters(function_expr = "SPARSim::SPARSim_estimate_parameter_from_data",
                                                  other_prior = other_prior,
                                                  step = "estimation")

  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using SPARSim\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- do.call(SPARSim::SPARSim_estimate_parameter_from_data, estimate_formals)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by SPARSim
#'
#' @param parameters A object generated by \code{\link[SPARSim]{SPARSim_simulation}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @import SPARSim
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#' @importFrom SingleCellExperiment counts colData rowData
#' @importFrom stats runif
#'
#' @export
#'
SPARSim_simulation <- function(parameters,
                               other_prior,
                               return_format,
                               verbose = FALSE,
                               seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("SPARSim", quietly = TRUE)){
    cat("SPARSim is not installed on your device\n")
    cat("Installing SPARSim...\n")
    devtools::install_gitlab("sysbiobig/sparsim")
  }
  other_prior[["dataset_parameter"]] <- parameters

  ## Batch
  if(!is.null(other_prior[["batch.condition"]])){
    other_prior[["output_batch_matrix"]] <- TRUE
    if(is.null(other_prior[["distribution"]])){
      stop("You must input the distribution formal of batch effect factors.")
    }else{
      assertthat::assert_that(length(unique(is.null(other_prior[["batch.condition"]]))) == length(other_prior[["distribution"]]),
                              msg = "The length of batch.condition must equal to the vector of distributions")
    }
    ## Default param A
    if(is.null(other_prior[["param_A"]])){
      for(w in 1:length(other_prior[["distribution"]])){
        dis <- other_prior[["distribution"]][w]
        if(dis == "normal"){
          cat("You do not set the statsitical parameters to describe the normal distribution and it will be set as 'mean = 0' by default. \n")
          other_prior[["param_A"]] <- BiocGenerics::append(other_prior[["param_A"]], 0)
        }
        if(dis == "gamma"){
          cat("You do not set the statsitical parameters to describe the gamma distribution and it will be set as 'scale = 1', 'shape = 1' by default. \n")
          other_prior[["param_A"]] <- BiocGenerics::append(other_prior[["param_A"]], 1)
        }
      }
    }
    ## Default param B
    if(is.null(other_prior[["param_B"]])){
      for(w in 1:length(other_prior[["distribution"]])){
        dis <- other_prior[["distribution"]][w]
        if(dis == "normal"){
          cat("You do not set the statsitical parameters to describe the normal distribution and it will be set as 'sd = 1' by default. \n")
          other_prior[["param_B"]] <- BiocGenerics::append(other_prior[["param_B"]], 1)
        }
        if(dis == "gamma"){
          cat("You do not set the statsitical parameters to describe the gamma distribution and it will be set as 'shape = 1' by default. \n")
          other_prior[["param_B"]] <- BiocGenerics::append(other_prior[["param_B"]], 1)
        }
      }
    }
    ## Check param length
    assertthat::assert_that(length(other_prior[["param_A"]]) == length(other_prior[["distribution"]]),
                                   msg = "The length of param_A must equal to the vector of distributions \n")
    assertthat::assert_that(length(other_prior[["param_B"]]) == length(other_prior[["distribution"]]),
                                   msg = "The length of param_B must equal to the vector of distributions \n")


    batch_set_tmp <- purrr::map(.x = seq_len(length(other_prior[["distribution"]])),
                                .f = function(id){
                                  SPARSim::SPARSim_create_batch(name = paste0("Batch", id),
                                                                distribution = other_prior[["distribution"]][id],
                                                                param_A = other_prior[["param_A"]][id],
                                                                param_B = other_prior[["param_B"]][id])
                                }) %>% stats::setNames(paste0("Batch_", seq_len(length(other_prior[["distribution"]]))))
    batch_set <- SPARSim::SPARSim_create_batch_set(batch_list = batch_set_tmp)
    batch_sample_association <- paste0("Batch", other_prior[["batch.condition"]])
    SPARSim_batch_parameter <-SPARSim::SPARSim_create_batch_parameter(batch_set = batch_set,
                                                                      batch_sample = batch_sample_association)
    other_prior[["batch_parameter"]] <- SPARSim_batch_parameter
  }
  ## DEGs
  if(!is.null(other_prior[["fc.group"]]) | !is.null(other_prior[["prob.group"]])){
    if(length(parameters) != 2){
      stop("We only now support 2 groups when you want to simulate DEGs")
    }
    cond_A_param <- parameters[[1]]

    if(is.null(other_prior[["fc.group"]])){
      cat("You do not point the fold change of DEGs between two groups, we will set it as 2 \n")
      other_prior[["fc.group"]] <- 2
    }
    if(is.null(other_prior[["prob.group"]])){
      cat("You do not point the percent of DEGs, we will set it as 0.1 \n")
      other_prior[["prob.group"]] <- 0.1
    }
    n_genes <- length(parameters[[1]][['intensity']])
    set.seed(seed)
    not_DE_multiplier <- stats::runif(n = n_genes*(1-other_prior[["prob.group"]]),
                                      min = 1/other_prior[["fc.group"]]+0.001,
                                      max = other_prior[["fc.group"]]-0.001)

    set.seed(seed)
    DE_multiplier <- c(stats::runif(n = ceiling(n_genes*other_prior[["prob.group"]]/2),
                                    min = 1/other_prior[["fc.group"]],
                                    max = 1/other_prior[["fc.group"]]),
                       stats::runif(n = floor(n_genes*other_prior[["prob.group"]]/2),
                                    min = other_prior[["fc.group"]],
                                    max = other_prior[["fc.group"]]))

    # In this example, the first 1000 genes will be the DE ones, while the last 16128 will be the not DE ones
    fold_change_multiplier <- c(DE_multiplier, not_DE_multiplier)


    ## STEP 3: Use SPARSim built-in function to create a simulation parameter with DE genes
    cond_B_param <- parameters[[2]]
    cond_B_param <- SPARSim::SPARSim_create_DE_genes_parameter(sim_param = cond_A_param,
                                                               fc_multiplier = fold_change_multiplier,
                                                               N_cells = length(cond_B_param[["lib_size"]]),
                                                               lib_size_DE = cond_B_param[["lib_size"]],
                                                               condition_name = "cond_B")

    SPARSim_param_with_DE <- list(cond_A = cond_A_param, cond_B = cond_B_param)
    other_prior[["dataset_parameter"]] <- SPARSim_param_with_DE
  }

  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################

  simulate_formals <- simutils::change_parameters(function_expr = "SPARSim::SPARSim_simulation",
                                                  other_prior = other_prior,
                                                  step = "simulation")

  condition_num <- length(parameters)
  cell_num <- c()
  for(i in 1:condition_num){
    tmp <- length(parameters[[i]][["lib_size"]])
    cell_num <- BiocGenerics::append(cell_num, tmp)
  }
  cell_num <- sum(cell_num)

  ## Batches
  if(is.null(simulate_formals[["batch_parameter"]])){
    nBatches <- 0
  }else{
    nBatches <- length(simulate_formals[["batch_parameter"]][["batch_set"]])
  }

  ## Group
  if(!is.null(other_prior[["fc.group"]])){
    fc.group <- other_prior[["fc.group"]]
  }else{
    fc.group <- 0
  }
  if(!is.null(other_prior[["prob.group"]])){
    prob.group <- other_prior[["prob.group"]]
  }else{
    prob.group <- 0
  }
  groups <- length(simulate_formals[["dataset_parameter"]])
  # Return to users
  cat(glue::glue("nCells: {cell_num}"), "\n")
  cat(glue::glue("nGenes: {length(parameters[[1]][['intensity']])}"), "\n")
  cat(glue::glue("nGroups: {groups}"), "\n")
  cat(glue::glue("fc.group: {fc.group}"), "\n")
  cat(glue::glue("prob.group: {prob.group}"), "\n")
  cat(glue::glue("nBatches: {nBatches}"), "\n")


  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using SPARSim\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- do.call(SPARSim::SPARSim_simulation, simulate_formals))
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  ## counts
  counts <- simulate_result[["count_matrix"]]
  group_index <- which(as.numeric(stringr::str_extract_all(colnames(counts), pattern = "[0-9]+", simplify = T)) == 1)
  group <- c()
  for(i in 1:length(group_index)){
    group_num <- group_index[i]
    if(i < length(group_index)){
      group_tmp <- rep(paste0("Group", i), (group_index[i+1]-1))
      group <- BiocGenerics::append(group, group_tmp)
    }else{
      group_tmp <- rep(paste0("Group", i), (ncol(counts)-group_index[i]+1))
      group <- BiocGenerics::append(group, group_tmp)
    }
  }
  colnames(counts) <- paste0("Cell", 1:ncol(counts))
  rownames(counts) <- paste0("Gene", 1:nrow(counts))
  ## col_data
  if(!is.null(simulate_formals[["batch_parameter"]])){
    batch <- paste0("Batch", other_prior[["batch.condition"]])
    col_data <- data.frame("cell_name" = colnames(counts),
                           "group" = group,
                           "batch" = batch)
  }else{
    col_data <- data.frame("cell_name" = colnames(counts),
                           "group" = group)
  }


  ## row_data
  if(!is.null(other_prior[["fc.group"]])){
    de_genes <- c(rep(TRUE, n_genes*other_prior[["prob.group"]]),
                  rep(FALSE, n_genes-n_genes*other_prior[["prob.group"]]))
    fc <- c(DE_multiplier, not_DE_multiplier)
    row_data <- data.frame("gene_name" = rownames(counts),
                           "de_genes" = de_genes,
                           "fc" = fc)
  }else{
    row_data <- data.frame("gene_name" = rownames(counts))
  }


  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)

  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

