#' Estimate Parameters From Real Datasets by ESCO
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{escoEstimate} function in ESCO package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom ESCO escoEstimate newescoParams
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
ESCO_estimation <- function(ref_data,
                            other_prior,
                            verbose = FALSE,
                            seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("ESCO", quietly = TRUE)){
    cat("ESCO is not installed on your device\n")
    cat("Installing ESCO...\n")
    devtools::install_github("JINJINT/ESCO")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  other_prior[["counts"]] <- ref_data
  if(is.null(other_prior[["group.condition"]])){
    other_prior[["group"]] <- FALSE
    other_prior[["cellinf"]] <- NULL
  }else{
    other_prior[["group"]] <- TRUE
    other_prior[["cellinf"]] <- other_prior[["group.condition"]]
  }
  other_prior[["params"]] <- ESCO::newescoParams()
  estimate_formals <- simutils::change_parameters(function_expr = "ESCO::escoEstimate",
                                                  other_prior = other_prior,
                                                  step = "estimation")
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using ESCO\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- do.call(ESCO::escoEstimate, estimate_formals)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by ESCO
#'
#' @param parameters A object generated by \code{\link[ESCO]{escoEstimate}}
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom ESCO escoEstimate
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#'
#' @export
#'
ESCO_simulation <- function(parameters,
                            return_format,
                            other_prior,
                            verbose = FALSE,
                            seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("ESCO", quietly = TRUE)){
    cat("ESCO is not installed on your device\n")
    cat("Installing ESCO...\n")
    devtools::install_github("JINJINT/ESCO")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  assertthat::assert_that(class(parameters) == "escoParams")

  # Get params to check
  params_check <- splatter::getParams(parameters, c("nCells",
                                                    "nGenes",
                                                    "nGroups",
                                                    "group.prob"))

  # Return to users
  cat(glue::glue("nCells: {params_check[['nCells']]}"), "\n")
  cat(glue::glue("nGenes: {params_check[['nGenes']]}"), "\n")
  cat(glue::glue("nGroups: {params_check[['nGroups']]}"), "\n")
  cat(glue::glue("prob.group: {params_check[['group.prob']]}"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using ESCO\n")
  }
  # Seed
  parameters <- splatter::setParam(parameters, name = "seed", value = seed)
  # Estimation
  tryCatch({
    if(!is.null(other_prior[["trajectory"]])){
      cat("Simulating trajectory datasets by ESCO")
      submethod <- "traj"
    }else{
      if(params_check[["nGroups"]] == 1){
        submethod <- "single"
      }else if(params_check[["nGroups"]] != 1){
        submethod <- "groups"
      }
    }
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- ESCO::escoSimulate(parameters,
                                            type = submethod,
                                            verbose = verbose))
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

