#' Estimate Parameters From Real Datasets by ESCO
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{escoEstimate} function in ESCO package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom ESCO escoEstimate newescoParams
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
ESCO_estimation <- function(ref_data,
                            other_prior,
                            verbose = FALSE,
                            seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("ESCO", quietly = TRUE)){
    cat("ESCO is not installed on your device\n")
    cat("Installing ESCO...\n")
    devtools::install_github("JINJINT/ESCO")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  other_prior[["counts"]] <- ref_data
  if(is.null(other_prior[["group.condition"]])){
    other_prior[["group"]] <- FALSE
    other_prior[["cellinfo"]] <- NULL
  }else{
    other_prior[["group"]] <- TRUE
    other_prior[["cellinfo"]] <- other_prior[["group.condition"]]
  }
  other_prior[["params"]] <- ESCO::newescoParams()
  other_prior[["dirname"]] <- "./"
  ## tree
  if(other_prior[["tree"]] | other_prior[["traj"]]){
    tree <- simutils::make_trees(ref_data = ref_data,
                                 group = other_prior[["cellinfo"]],
                                 is_Newick = FALSE,
                                 is_parenthetic = TRUE,
                                 return_group = TRUE)
    group <- tree[["group"]]
    tree <- tree[["phyla"]]
  }else{
    tree <- NULL
  }
  estimate_formals <- simutils::change_parameters(function_expr = "ESCO::escoEstimate",
                                                  other_prior = other_prior,
                                                  step = "estimation")
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using ESCO\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- do.call(ESCO::escoEstimate, estimate_formals)
    )
  }, error = function(e){
    as.character(e)
  })
  if(!is.null(tree)){
    estimate_result <- list(estimate_result = estimate_result,
                            tree = tree,
                            group = group)
  }
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by ESCO
#'
#' @param parameters A object generated by \code{\link[ESCO]{escoEstimate}}
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom ESCO escoEstimate
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#'
#' @export
#'
ESCO_simulation <- function(parameters,
                            return_format,
                            other_prior,
                            verbose = FALSE,
                            seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("ESCO", quietly = TRUE)){
    cat("ESCO is not installed on your device\n")
    cat("Installing ESCO...\n")
    devtools::install_github("JINJINT/ESCO")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(length(parameters) == 3){
    tree <- parameters[["tree"]]
    group <- parameters[["group"]]
    parameters <- parameters[["estimate_result"]]
  }
  assertthat::assert_that(class(parameters) == "escoParams")
  # nCells
  if(!is.null(other_prior[["nCells"]])){
    parameters <- splatter::setParam(parameters, name = "nCells", value = other_prior[["nCells"]])
  }
  # nGenes
  if(!is.null(other_prior[["nGenes"]])){
    parameters <- splatter::setParam(parameters, name = "nGenes", value = other_prior[["nGenes"]])
  }
  # nGroup
  if(!is.null(group)){
    parameters <- splatter::setParam(parameters, name = "nGroups", value = length(unique(group)))
  }
  if(!is.null(other_prior[["prob.group"]])){
    parameters <- splatter::setParam(parameters,
                                     name = "group.prob",
                                     value = other_prior[["prob.group"]])

  }else{
    nGroups <- splatter::getParam(parameters, name = "nGroups")
    prob.group <- c(rep(1/nGroups, nGroups-1),
                    1 - c(1/nGroups * c(nGroups-1)))
    parameters <- splatter::setParam(parameters,
                                     name = "group.prob",
                                     value = prob.group)
  }
  # Get params to check
  params_check <- splatter::getParams(parameters, c("nCells",
                                                    "nGenes",
                                                    "nGroups",
                                                    "group.prob",
                                                    "de.prob"))

  # Return to users
  cat(glue::glue("nCells: {params_check[['nCells']]}"), "\n")
  cat(glue::glue("nGenes: {params_check[['nGenes']]}"), "\n")
  cat(glue::glue("nGroups: {params_check[['nGroups']]}"), "\n")
  cat(glue::glue("prob.group: {params_check[['group.prob']]}"), "\n")
  cat(glue::glue("de.group: {params_check[['de.prob']]}"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using ESCO\n")
  }
  # Seed
  parameters <- splatter::setParam(parameters, name = "seed", value = seed)
  # Estimation
  tryCatch({
    if(!is.null(other_prior[["tree"]])){
      cat("Simulating trajectory of trees datasets by ESCO \n")
      submethod <- "tree"
      parameters <- splatter::setParam(parameters, name = "tree", value = tree)
    }else if(!is.null(other_prior[["traj"]])){
      cat("Simulating trajectory datasets by ESCO")
      submethod <- "traj"
      parameters <- splatter::setParam(parameters, name = "tree", value = tree)
    }else{
      if(params_check[["nGroups"]] == 1){
        submethod <- "single"
      }else if(params_check[["nGroups"]] != 1){
        submethod <- "groups"
      }
    }
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- ESCO::escoSimulate(parameters,
                                            type = submethod,
                                            verbose = verbose))
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

