#' Estimate Parameters From Real Datasets by muscat
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{prepSim} function in muscat package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param seed An integer of a random seed.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @importFrom peakRAM peakRAM
#' @importFrom muscat prepSim prepSCE
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
muscat_estimation <- function(ref_data,
                              verbose = FALSE,
                              other_prior,
                              seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("muscat", quietly = TRUE)){
    cat("muscat is not installed on your device\n")
    cat("Installing muscat...\n")
    devtools::install_github("HelenaLC/muscat")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  ## group
  if(is.null(other_prior[["group.condition"]])){
    other_prior[["group_id"]] <- rep("A", ncol(ref_data))
  }
  ## cluster
  if(is.null(other_prior[["cluster_id"]])){
    other_prior[["cluster_id"]] <- rep("A", ncol(ref_data))
  }

  col_data <- data.frame("sample_id" = other_prior[["cluster_id"]],
                         "group_id" = other_prior[["group_id"]],
                         "cluster_id" = other_prior[["cluster_id"]])

  ref_data <- SingleCellExperiment::SingleCellExperiment(list(counts = ref_data),
                                                         colData = col_data)

  ref_data <- muscat::prepSCE(x = ref_data)

  other_prior[["x"]] <- ref_data
  if(is.null(other_prior[["min_count"]])){
    other_prior[["min_count"]] <- 1
  }
  if(is.null(other_prior[["min_cells"]])){
    other_prior[["min_cells"]] <- 10
  }
  if(is.null(other_prior[["min_genes"]])){
    other_prior[["min_genes"]] <- 100
  }
  estimate_formals <- simutils::change_parameters(function_expr = "muscat::prepSim",
                                                  other_prior = other_prior,
                                                  step = "estimation")
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using SparseDC\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- muscat::prepSim(x = estimate_formals[["x"]],
                                         min_count = estimate_formals[["min_count"]],
                                         min_cells = estimate_formals[["min_cells"]],
                                         min_genes = estimate_formals[["min_genes"]],
                                         min_size = NULL,
                                         group_keep = estimate_formals[["group_keep"]],
                                         verbose = estimate_formals[["verbose"]])
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by muscat
#'
#' @param parameters A object generated by \code{\link[muscat]{prepSim}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom muscat simData
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#' @importFrom SingleCellExperiment counts colData rowData
#' @importFrom Seurat as.Seurat
#' @importFrom SeuratDisk SaveH5Seurat Convert
#' @importFrom stringr str_replace
#'
#' @export
#'
muscat_simulation <- function(parameters,
                              other_prior,
                              return_format,
                              verbose = FALSE,
                              seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("muscat", quietly = TRUE)){
    cat("muscat is not installed on your device\n")
    cat("Installing muscat...\n")
    devtools::install_github("HelenaLC/muscat")
  }
  other_prior[["x"]] <- parameters
  ## nCells
  if(!is.null(other_prior[["nCells"]])){
    other_prior[["nc"]] <- other_prior[["nCells"]]
  }else{
    other_prior[["nc"]] <- ncol(parameters)
  }
  ## nGenes
  if(!is.null(other_prior[["nGenes"]])){
    other_prior[["ng"]] <- other_prior[["nGenes"]]
  }else{
    other_prior[["ng"]] <- nrow(parameters)
  }
  ## fc.group
  if(!is.null(other_prior[["fc.group"]])){
    other_prior[["lfc"]] <- other_prior[["fc.group"]]
  }else{
    other_prior[["lfc"]] <- 2
  }
  ## de.group
  if(!is.null(other_prior[["de.group"]])){
    other_prior[["p_dd"]] <- c(1-other_prior[["de.group"]],
                               0, other_prior[["de.group"]], 0, 0, 0)
  }else{
    other_prior[["p_dd"]] <- c(1,0,0,0,0,0)
  }
  ## nGroups
  if(is.null(other_prior[["nGroups"]])){
    other_prior[["nGroups"]] <- 1
  }
  if(other_prior[["nGroups"]] == 1){
    other_prior[["dd"]] <- FALSE
  }else{
    other_prior[["ns"]] <- 2
    other_prior[["dd"]] <- TRUE
    other_prior[["paired"]] <- TRUE
  }
  ## phylo_pars
  other_prior[["phylo_pars"]] <- c(0, 3)
  other_prior[["force"]] <- TRUE
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  simulate_formals <- simutils::change_parameters(function_expr = "muscat::simData",
                                                  other_prior = other_prior,
                                                  step = "simulation")
  nGroups <- ifelse(simulate_formals[["dd"]], 2, 1)
  de.group <- simulate_formals[["p_dd"]][3]/sum(simulate_formals[["p_dd"]])
  # Return to users
  cat(glue::glue("nCells: {simulate_formals[['nc']]}"), "\n")
  cat(glue::glue("nGenes: {simulate_formals[['ng']]}"), "\n")
  cat(glue::glue("nGroups: {nGroups}"), "\n")
  cat(glue::glue("de.group: {de.group}"), "\n")
  cat(glue::glue("fc.group: {simulate_formals[['lfc']]}"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using muscat\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- do.call(muscat::simData, simulate_formals)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  colnames(simulate_result) <- paste0("Cell", 1:ncol(simulate_result))
  rownames(simulate_result) <- paste0("Gene", 1:nrow(simulate_result))
  gene_info <- metadata(simulate_result)$gene_info
  rowData(simulate_result) <- gene_info %>%
    transmute("gene_name" = rownames(simulate_result),
              "de_genes" = case_when(
                gene_info$"category" == "ee" ~ FALSE,
                gene_info$"category" == "de" ~ TRUE
              ),
              "fc" = gene_info$"logFC")
  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

