#' Estimate Parameters From Real Datasets by hierarchicell
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{compute_data_summaries} function in hierarchicell package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param seed An integer of a random seed.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @importFrom peakRAM peakRAM
#' @importFrom hierarchicell filter_counts compute_data_summaries
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
hierarchicell_estimation <- function(ref_data,
                                     verbose = FALSE,
                                     other_prior,
                                     seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("hierarchicell", quietly = TRUE)){
    cat("hierarchicell is not installed on your device\n")
    cat("Installing hierarchicell...\n")
    devtools::install_github("kdzimm/hierarchicell")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  ref_data <- hierarchicell::filter_counts(ref_data,
                                           gene_thresh = 0,
                                           cell_thresh = 0)
  if(is.null(other_prior[["type"]])){
    cat("You do not set the type of the data (Raw or Norm), we will set 'Raw' by default")
    other_prior[["type"]] <- "Raw"
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using hierarchicell\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- hierarchicell::compute_data_summaries(expr = ref_data,
                                                               type = other_prior[["type"]])
    )
  }, error = function(e){
    as.character(e)
  })
  estimate_result[["hierarchicell_data_dim"]] <- dim(ref_data)
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by hierarchicell
#'
#' @param parameters A object generated by \code{\link[hierarchicell]{simulate_hierarchicell}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom hierarchicell simulate_hierarchicell
#'
#' @export
#'
hierarchicell_simulation <- function(parameters,
                                     other_prior,
                                     return_format,
                                     verbose = FALSE,
                                     seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("hierarchicell", quietly = TRUE)){
    cat("hierarchicell is not installed on your device\n")
    cat("Installing hierarchicell...\n")
    devtools::install_github("kdzimm/hierarchicell")
  }
  other_prior[["data_summaries"]] <- parameters
  ## nCells
  if(!is.null(other_prior[["nCells"]])){
    if(length(other_prior[["nCells"]]) == 1){
      other_prior[["cells_per_control"]] <- ceiling(other_prior[["nCells"]]/2)
      other_prior[["cells_per_case"]] <- floor(other_prior[["nCells"]]/2)
    }
    if(length(other_prior[["nCells"]]) == 2){
      other_prior[["cells_per_control"]] <- other_prior[["nCells"]][1]
      other_prior[["cells_per_case"]] <- other_prior[["nCells"]][2]
    }
  }else{
    other_prior[["nCells"]] <- parameters[["hierarchicell_data_dim"]][2]
    other_prior[["cells_per_control"]] <- ceiling(other_prior[["nCells"]]/2)
    other_prior[["cells_per_case"]] <- floor(other_prior[["nCells"]]/2)
  }
  ## nGenes
  if(!is.null(other_prior[["nGenes"]])){
    other_prior[["n_genes"]] <- other_prior[["nGenes"]]
  }else{
    other_prior[["n_genes"]] <- parameters[["hierarchicell_data_dim"]][1]
  }
  ## fc.group
  if(!is.null(other_prior[["fc.group"]])){
    other_prior[["foldchange"]] <- other_prior[["fc.group"]]
  }else{
    other_prior[["foldchange"]] <- 2
  }
  ## case and control
  if(is.null(other_prior[["n_cases"]])){
    other_prior[["n_cases"]] <- 1
  }
  if(is.null(other_prior[["n_controls"]])){
    other_prior[["n_controls"]] <- 1
  }
  ## n_per_group
  if(is.null(other_prior[["n_per_group"]])){
    other_prior[["n_per_group"]] <- 1
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  simulate_formals <- simutils::change_parameters(function_expr = "hierarchicell::simulate_hierarchicell",
                                                  other_prior = other_prior,
                                                  step = "simulation")
  # Return to users
  cat(glue::glue("nCells: {simulate_formals[['cells_per_control']] + simulate_formals[['cells_per_case']]}"), "\n")
  cat(glue::glue("nGenes: {simulate_formals[['n_genes']]}"), "\n")
  cat(glue::glue("nGroups: 2"), "\n")
  cat(glue::glue("fc.group: {simulate_formals[['foldchange']]}"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using hierarchicell\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- do.call(hierarchicell::simulate_hierarchicell, simulate_formals)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  group <- paste0("Group", ifelse(simulate_result$Status=="Case", 2, 1))
  if(length(group) != other_prior[["nCells"]]){
    group <- group[1:other_prior[["nCells"]]]
    simulate_result <- simulate_result[1:other_prior[["nCells"]], ]
  }
  simulate_result <- t(simulate_result[, -c(1:3)])
  ## colnames rownames
  colnames(simulate_result) <- paste0("Cell", 1:ncol(simulate_result))
  rownames(simulate_result) <- paste0("Gene", 1:nrow(simulate_result))
  counts <- simulate_result
  ## col_data
  col_data <- data.frame("cell_name" = colnames(counts),
                         "group" = group)
  ## row data
  row_data <- data.frame("gene_name" = rownames(counts),
                         "de_genes" = rep("not known", nrow(counts)),
                         "fc" = rep("not known", nrow(counts)))
  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)

  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

