#' Estimate Parameters From Real Datasets by dropsim
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{fit_parameters} function in hierarchicell package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom dropsim fit_parameters
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
dropsim_estimation <- function(ref_data,
                               verbose = FALSE,
                               seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("dropsim", quietly = TRUE)){
    cat("dropsim is not installed on your device\n")
    cat("Installing dropsim...\n")
    devtools::install_github("marchinilab/dropsim")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using dropsim\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- dropsim::fit_parameters(ref_data)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by dropsim
#'
#' @param parameters A object generated by \code{\link[dropsim]{simulateDGE}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom dropsim simulateDGE
#'
#' @export
#'
dropsim_simulation <- function(parameters,
                               other_prior,
                               return_format,
                               verbose = FALSE,
                               seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("dropsim", quietly = TRUE)){
    cat("dropsim is not installed on your device\n")
    cat("Installing dropsim...\n")
    devtools::install_github("marchinilab/dropsim")
  }
  other_prior[["parameters"]] <- parameters
  ## nCells
  if(!is.null(other_prior[["nCells"]])){
    slot(other_prior[["parameters"]], "n_cells") <- as.integer(other_prior[["nCells"]])
  }
  ## nGenes
  if(!is.null(other_prior[["nGenes"]])){
    slot(other_prior[["parameters"]], "n_genes") <- as.integer(other_prior[["nGenes"]])
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  simulate_formals <- simutils::change_parameters(function_expr = "dropsim::simulateDGE",
                                                  other_prior = other_prior,
                                                  step = "simulation")
  # Return to users
  cat(glue::glue("nCells: {other_prior[['parameters']]@n_cells}"), "\n")
  cat(glue::glue("nGenes: {other_prior[['parameters']]@n_genes}"), "\n")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using dropsim\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      simulate_result <- do.call(dropsim::simulateDGE, simulate_formals)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  counts <- as.matrix(simulate_result[["counts"]])
  ## colnames rownames
  colnames(counts) <- paste0("Cell", 1:ncol(counts))
  rownames(counts) <- paste0("Gene", 1:nrow(counts))
  ## col_data
  col_data <- data.frame("cell_name" = colnames(counts),
                         "group" = rep("Group1", ncol(counts)),
                         "batch" = rep("Batch1", ncol(counts)))
  ## row data
  row_data <- data.frame("gene_name" = rownames(counts))
  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)

  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

