#' Estimate Parameters From Real Datasets by phenopath
#'
#' This function is used to estimate useful parameters from a real dataset by
#' using \code{phenoEstimate} function in Splatter package.
#'
#' @param ref_data A count matrix. Each row represents a gene and each column
#' represents a cell.
#' @param verbose Logical.
#' @param seed An integer of a random seed.
#' @importFrom peakRAM peakRAM
#' @importFrom splatter phenoEstimate
#'
#' @return A list contains the estimated parameters and the results of execution
#' detection.
#' @export
#'
phenopath_estimation <- function(ref_data, verbose = FALSE, seed){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("splatter", quietly = TRUE)){
    cat("Splatter is not installed on your device\n")
    cat("Installing splatter...\n")
    BiocManager::install("splatter")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!is.matrix(ref_data)){
    ref_data <- as.matrix(ref_data)
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    cat("Estimating parameters using phenopath\n")
  }
  # Seed
  set.seed(seed)
  # Estimation
  tryCatch({
    # Estimate parameters from real data and return parameters and detection results
    estimate_detection <- peakRAM::peakRAM(
      estimate_result <- splatter::phenoEstimate(ref_data)
    )
  }, error = function(e){
    as.character(e)
  })
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  estimate_output <- list(estimate_result = estimate_result,
                          estimate_detection = estimate_detection)
  return(estimate_output)
}


#' Simulate Datasets by phenopath
#'
#' @param ref_data NULL or reference data if you want to simulate trajectory data.
#' @param parameters A object generated by \code{\link[splatter]{phenoEstimate}}
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them. In
#' simulation step, the number of cells, genes, groups, batches, the percent of
#' DEGs and other variables are usually customed, so before simulating a dataset
#' you must point it out.
#' @param return_format A character. Alternatives choices: list, SingleCellExperiment,
#' Seurat, h5ad
#' @param verbose Logical. Whether to return messages or not.
#' @param seed A random seed.
#'
#' @importFrom splatter getParams setParam
#'
#' @export
#'
phenopath_simulation <- function(ref_data = NULL,
                                 parameters,
                                 other_prior,
                                 return_format,
                                 verbose = FALSE,
                                 seed
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("splatter", quietly = TRUE)){
    cat("Splatter is not installed on your device\n")
    cat("Installing splatter...\n")
    BiocManager::install("phenopath")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  assertthat::assert_that(class(parameters) == "PhenoParams")
  # nCells
  if(!is.null(other_prior[["nCells"]])){
    parameters <- splatter::setParam(parameters, name = "nCells", value = other_prior[["nCells"]])
  }
  # nGenes
  if(!is.null(other_prior[["nGenes"]])){
    parameters <- splatter::setParam(parameters, name = "nGenes", value = other_prior[["nGenes"]])
  }

  # Get params to check
  params_check <- splatter::getParams(parameters, c("nCells",
                                                    "nGenes"))

  # Return to users
  cat(glue::glue("nCells: {params_check[['nCells']]}"), "\n")
  cat(glue::glue("nGenes: {params_check[['nGenes']]}"), "\n")

  # Get the parameters we are going to use
  nCells <- splatter::getParam(parameters, "nCells")
  nGenes <- splatter::getParam(parameters, "nGenes")
  n.de <- splatter::getParam(parameters, "n.de")
  n.pst <- splatter::getParam(parameters, "n.pst")
  n.pst.beta <- splatter::getParam(parameters, "n.pst.beta")
  n.de.pst.beta <- splatter::getParam(parameters, "n.de.pst.beta")
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    cat("Simulating datasets using phenopath\n")
  }
  # Seed
  parameters <- splatter::setParam(parameters, name = "seed", value = seed)
  # Estimation
  tryCatch({
    simulate_detection <- peakRAM::peakRAM(
      pheno_sim <- phenopath::simulate_phenopath(N = nCells,
                                                 G_de = n.de,
                                                 G_pst = n.pst,
                                                 G_pst_beta = n.pst.beta,
                                                 G_de_pst_beta = n.de.pst.beta))
  }, error = function(e){
    as.character(e)
  })
  # Row and column names
  cell.names <- paste0("Cell", seq_len(nCells))
  gene.names <- paste0("Gene", seq_len(nGenes))
  # Counts
  exprs <- t(pheno_sim$y)
  counts <- 2 ^ exprs - 1
  counts[counts < 0] <- 0
  counts <- round(counts)
  rownames(counts) <- gene.names
  colnames(counts) <- cell.names
  # Col data
  cells <- data.frame(Cell = cell.names,
                      Pseudotime = pheno_sim$z)
  rownames(cells) <- cell.names
  # Row data
  features <- data.frame(Gene = gene.names,
                         Alpha = pheno_sim$parameters$alpha,
                         Lambda = pheno_sim$parameters$lambda,
                         Beta = pheno_sim$parameters$beta,
                         Regime = pheno_sim$parameters$regime)
  rownames(features) <- gene.names
  # SCE object
  simulate_result <- SingleCellExperiment::SingleCellExperiment(assays = list(counts = counts),
                                                                rowData = features,
                                                                colData = cells)
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  simulate_result <- simutils::data_conversion(SCE_object = simulate_result,
                                               return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  simulate_output <- list(simulate_result = simulate_result,
                          simulate_detection = simulate_detection)
  return(simulate_output)
}

